import { Amplify } from 'aws-amplify';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

// import './globals.css'
import ThemeRegistry from "../lib/muiRegistry";
import { Providers } from "../store/storeProvider";
import config from './../amplifyconfiguration.json';

const inter = Inter({ subsets: ["latin"] });

Amplify.configure(config);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <ThemeRegistry options={{ key: "mui" }}>
          {" "}
          <>
            <div style={{ display: "flex", justifyContent: "space-evenly" }}>
              <Link href="/">Home</Link>
              <Link href="/posts">Posts</Link>
              <Link href="/redux">Redux Counter</Link>
              <Link href="/mui">Mui</Link>
              <Link href="/ag-grid">AG Grid</Link>
            </div>
            <Providers>{children}</Providers>
          </>
        </ThemeRegistry>
      </body>
    </html>
  );
}
